/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RoyaltySplitter } from "./RoyaltySplitter";
export * as factories from "./factories";
export { RoyaltySplitter__factory } from "./factories/RoyaltySplitter__factory";
